### ISSUE TITLE
谢谢

### ISSUE THREAD

**Issue by rcj60560** [hehuapei/study-demo#1]
学习一下

**Comment by hehuapei** [comment]
不客气,我也是看着网上的资料自己摸索着做的,如果有更好的做法,希望可以指教!

**Comment by rcj60560** [comment]
@hehuapei 微信加一波 撒 我加你！

**Comment by hehuapei** [comment]
> @hehuapei 微信加一波 撒 我加你！

可以加我QQ 34350696 互相交流~!
